services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - /node_modules
      - .:/app
      - /app/node_modules
    command: ["pnpm", "test"]
